version: '2.2'
services:
  fastapitemplate:
    image: xgbimage
    build: .
    command: uvicorn main:app --port ${CONTAINER_PORT} --host 0.0.0.0 
    container_name: xgbcontainer
    environment:
      - HOST_PORT
      - CONTAINER_PORT
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}" 
